# Generated by Django 3.2.9 on 2021-12-09 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicino', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Cure',
        ),
    ]
